version: '3.7'
services:

  recommendation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.4.22
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db"
    environment:
     - MONGO_DATA_DIR=/data/db
     - MONGO_LOG_DIR=/dev/null
     - MONGODB_USER="user"
     - MONGODB_USER="pass"

